server:
  port: 8081
spring:
  rabbitmq:
    addresses: localhost
    username: admin
    password: admin
    virtual-host: my_vhost
    #开启生产者消息确认
    publisher-confirms: true
    publisher-returns: true

#  redis:
#    # Redis服务器地址
#    host: 150.158.17.217
#    # Redis服务器端口号
#    port: 6479
#    # 使用的数据库索引，默认是0
#    database: 0
#    # 连接超时时间
#    timeout: 1800000
#    # 设置密码
#    password: "123456"
#    lettuce:
#      pool:
#        # 最大阻塞等待时间，负数表示没有限制
#        max-wait: -1
#        # 连接池中的最大空闲连接
#        max-idle: 5
#        # 连接池中的最小空闲连接
#        min-idle: 0
#        # 连接池中最大连接数，负数表示没有限制
#        max-active: 20
